# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
fos_ck_editor:
    configs:
        admin_config:
            toolbar: full 
            uiColor: "#e2e2e2"
        user_config:
            toolbar: basic
            uiColor: "#e2e2e2"
