vich_uploader:
    db_driver: orm

    mappings:
        photos:
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            directory_namer: App\Upload\PhotoDirectoryNamer
            uri_prefix: /images
            upload_destination: '%kernel.project_dir%/public/images'
