# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'fr'
    photos_directory: '%kernel.project_dir%/public/uploads/photos'
    home_page_images_directory: 'images/home_page'
    advert_active_duration: '1 year' 
    limit_creation_periods: '2 years'
    minimum_creation_periods: '1 year'
    rental_automatically_confirmation: '15 days'
    periods_durations: [ "Week-end", "Long week-end", "Semaine" ]
    administrateur_email: 'administrateur@roadtrip.com'    
    contestation_email: "contestation@roadtrip.com"    
    backend_admin_user: "backendAdminUser"
    administrateur_firstname: 'Administrator'
    administrateur_name: 'Roadtrip'
    registration_email_subject: 'Welcome to Roadtrip'
    contact_owner_subject: 'Contact about your advert on Raodtrip'
    thread_subject: 'New message in your thread on Roadtrip'
    booking_request_subject: 'New booking request from Roadtrip'
    booking_request_refused_subject: 'Your request booking is refused'
    booking_request_accepted_subject: 'Your request booking is accepted'
    password_Resetting_email_subject: 'Renew password on Roadtrip'
    rating_email_subject: "Waiting for lease approval"
    rating_approval_subject: "New assessment pending approval"
    rating_not_confirmed_rental_email_subject: "Rent related to your unconfirmed evaluation"
    succeed_payment_email_subject: 'Accepted payment'
    stripe_account: acct_1EbuOxJ448Kc3t3S
    stripe_public_key: pk_test_lFbnmMuNBNktwcox9MhvdFnA00txD1vT93
    stripe_secret_key: sk_test_A04LvA0jEAUKuBZnez1afI4t00OrQwUAgN
    stripe_endpoint_secret: whsec_4Ao9Yz2J9n6l4r9e3eb6pLHCFVlaj77K
    stripe_betas: payment_intent_beta_3
    bills_directory: '%kernel.project_dir%/bills'
    payment:
        currency: EUR
        decimal: true
        premium_amount: 1
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Listener\PhotoCacheSubscriber:
        tags:
            - { name: doctrine.event_subscriber }
        arguments: [ '@service_container' ]

    App\Listener\CalendarListener:
        tags:
            - { name: 'kernel.event_listener', event: 'calendar.set_data', method: load }
    App\Upload\PhotoDirectoryNamer:
        public: true

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones 
